update local version of bounded-local

diff --git a/multi-node/vagrant/vol-plugins/bounded-local-controller b/multi-node/vagrant/vol-plugins/bounded-local-controller
--- a/multi-node/vagrant/vol-plugins/bounded-local-controller
+++ b/multi-node/vagrant/vol-plugins/bounded-local-controller
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION="0.6"
+VERSION="0.7"
 
 # Copyright 2016 The Kubernetes Authors.
 #
@@ -79,16 +79,16 @@ get_pod_metadata() {
 
         for META in namespace::namespace podname::pod labels::label
         do
-		METAKEY=${META%%::*}
-		METADISPLAY=${META##*::}
+                METAKEY=${META%%::*}
+                METADISPLAY=${META##*::}
                 for ELEMENT in $(lookup_metadata_item ${METAKEY} ${VOL})
                 do
                         if [[ -n "${ELEMENT}" ]]; then
                                 ELEMENT=$(echo ${ELEMENT} | sed -e 's/%20/ /g')
                                 if [[ "${ELEMENT}" =~ = ]]; then
                                         # structured key=value type fields become k8s_meta_key::value
-					KEY=${ELEMENT%%=*}	
-					VALUE=${ELEMENT##*=}
+                                        KEY=${ELEMENT%%=*}
+                                        VALUE=${ELEMENT##*=}
                                         [[ -z "${METALINE}" ]] && METALINE="k8s_${METADISPLAY}_${KEY,,}::${VALUE}" || METALINE+=" k8s_${METADISPLAY}_${KEY,,}::${VALUE}"
                                 else
                                         # simple value type fields become k8s_meta::value
@@ -119,15 +119,21 @@ check_logging_mirror() {
                 fi
         fi
 
-        # if using a log collector plugin then call out to check it and configure if needed. 
-	if [[ -n "${LOGGING_BACKEND_PLUGIN}" ]]; then
-        	if ! ${LOGGING_BACKEND_PLUGIN} check ${PODUID}; then
-                	if ! ${LOGGING_BACKEND_PLUGIN} add ${PODUID} "$(get_pod_metadata ${VOL})"; then
-				log "ERROR! Could not configure the log monitor via the ${LOGGING_BACKEND_PLUGIN} logging plugin."
-				return 1
-			fi
-        	fi
-	fi
+        # if using a log collector plugin then call out to check it and configure if needed.
+        if [[ -n "${LOGGING_BACKEND_PLUGIN}" ]]; then
+                log "Running ${LOGGING_BACKEND_PLUGIN} check ${PODUID}"
+                if ! ${LOGGING_BACKEND_PLUGIN} check ${PODUID}; then
+                        local META=$(get_pod_metadata ${VOL})
+                        log "POD META is ${META}"
+                        log "Running ${LOGGING_BACKEND_PLUGIN} add ${PODUID} \"${META}\""
+                        if ! ${LOGGING_BACKEND_PLUGIN} add ${PODUID} "${META}"; then
+                                log "ERROR! Could not configure the log monitor via the ${LOGGING_BACKEND_PLUGIN} logging plugin."
+                                return 1
+                        fi
+                fi
+        else
+                log "BACKEND LOGGING NOT ENABLED!"
+        fi
 
         return 0
 }
@@ -141,21 +147,22 @@ remove_logging_mirror() {
         local PODUID=${PODUID##*/}
         local LOGMOUNT="${LOGGING_PATH}/${PODUID}"
 
-	# Call out to the logging collector plugin to remove any local configuration
-	if [[ -n "${LOGGING_BACKEND_PLUGIN}" ]]; then
-		if ! ${LOGGING_BACKEND_PLUGIN} remove ${PODUID}; then
-			log "ERROR! Removing logging configuration via the ${LOGGING_BACKEND_PLUGIN} logging plugin."
-			return 1
-		fi
-	fi
+        # Call out to the logging collector plugin to remove any local configuration
+        if [[ -n "${LOGGING_BACKEND_PLUGIN}" ]]; then
+                log "Running ${LOGGING_BACKEND_PLUGIN} remove ${PODUID}"
+                if ! ${LOGGING_BACKEND_PLUGIN} remove ${PODUID}; then
+                        log "ERROR! Removing logging configuration via the ${LOGGING_BACKEND_PLUGIN} logging plugin."
+                        return 1
+                fi
+        fi
 
-	# remove the logging volume copy...
+        # remove the logging volume copy...
         if ismounted ${LOGMOUNT}; then
                 log "[CHANGE] Un-mounting and removing ${LOGMOUNT}"
                 umount -l ${LOGMOUNT}
                 rm -rf ${LOGMOUNT}
         fi
-	return 0
+        return 0
 }
 
 #################################################################################################################
@@ -164,6 +171,7 @@ remove_logging_mirror() {
 while true; do
         log "*** "
         log "*** Running bounded-local-controller (${VERSION}) main loop over ${VOLUME_PATH} "
+        log "LOGGING_BACKEND_PLUGIN=${LOGGING_BACKEND_PLUGIN}"
         log "*** "
         for VOL in ${VOLUME_PATH}/*
         do
@@ -177,9 +185,9 @@ while true; do
                 WHEN=$(cat ${VOL}/status | awk '{print $2}')
                 MNTPATH=$(cat ${VOL}/mountpath)
 
-		# always maintain logging mirror regarless of volume status (to give short lived pods a chance to log)
+                # always maintain logging mirror regarless of volume status (to give short lived pods a chance to log)
                 if [[ -f "${VOL}/mirror" ]]; then
-                	[[ $(cat "${VOL}/mirror") == "true" ]] && check_logging_mirror ${VOL}
+                        [[ $(cat "${VOL}/mirror") == "true" ]] && check_logging_mirror ${VOL}
                 fi
 
                 case ${STATUS} in
diff --git a/multi-node/vagrant/vol-plugins/bounded-local-splunk b/multi-node/vagrant/vol-plugins/bounded-local-splunk
--- a/multi-node/vagrant/vol-plugins/bounded-local-splunk
+++ b/multi-node/vagrant/vol-plugins/bounded-local-splunk
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION="0.1"
+VERSION="0.2"
 
 # Copyright 2016 The Kubernetes Authors.
 #
@@ -16,7 +16,7 @@ VERSION="0.1"
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# splunk-controller provides configuration for controlling a splunk 
+# splunk-controller provides configuration for controlling a splunk
 # universal forwarder with bounded-local volumes for log collection.
 
 # Configuration VARS
@@ -34,7 +34,7 @@ DEBUG="false"
 
 # Simplistic log handling (print to stdout).
 log() {
-        echo "$*"
+        echo "[SPLUNK_PLUGIN] $*"
 }
 
 # call the splunk forwarder REST API using curl.
@@ -48,7 +48,7 @@ splunk_api() {
   [[ "${DEBUG}" == "true" ]] && log "Calling $CALL"
   if ! RESULT=$(eval $CALL 2>&1)
   then
-    log "Splunk API CALL FAILED!"
+    log "splunk API CALL FAILED!"
     [[ "${DEBUG}" == "true"  ]] && log "${RESULT}"
     return 1
   else
@@ -65,16 +65,18 @@ escape_quotes() {
 # Add a universal forwarder config for a bounded-local volume with optional metadata
 add_splunk_monitor() {
         local PUID=$1
-	local META=$2
+        shift
+        local META=$*
+        log "meta is $META"
 
-	local SET_META=""
-	[[ -n "${META}" ]] && SET_META="-d \"_meta=$(escape_quotes ${META})\""
+        local SET_META=""
+        [[ -n "${META}" ]] && SET_META="-d \"_meta=$(escape_quotes ${META})\""
 
         splunk_api POST "/services/data/inputs/monitor" "-d \"name=/applogs/${PUID}/\"" && \
-	splunk_api POST "/services/properties/inputs/monitor%3A%2F%2F%2Fapplogs%2F${PUID}" "${SET_META} -d \"sourcetype=k8s-log\"" && \
+        splunk_api POST "/services/properties/inputs/monitor%3A%2F%2F%2Fapplogs%2F${PUID}" "${SET_META} -d \"sourcetype=k8s-log\"" && \
         splunk_api GET "/services/data/inputs/monitor/_reload"
         if [[ "$?" -eq 0 ]]; then
-                log "[CHANGE] Created splunk monitor and updated with pod metadata .. ok"
+                log "Created splunk monitor and updated with pod metadata .. ok"
                 splunk_api GET /services/properties/inputs/monitor%3A%2F%2F%2Fapplogs%2F${PUID}
         else
                 log "ERROR creating splunk monior!"
@@ -89,11 +91,10 @@ remove_splunk_monitor() {
         local PUID=$1
 
         log "Removing splunk monitor for ${PUID}"
-
         splunk_api DELETE "/services/data/inputs/monitor/%252Fapplogs%252F${PUID}"  && \
         splunk_api GET "/services/data/inputs/monitor/_reload"
         if [[ "$?" -eq 0 ]]; then
-                log "[CHANGE] Successfully removed splunk monitor .. ok"
+                log "Successfully removed splunk monitor .. ok"
         else
                 log "ERROR removing splunk monior!"
                 return 1
@@ -112,10 +113,10 @@ check_splunk_monitor() {
 }
 
 usage() {
-	echo "Usage: -"
-	echo "splunk-controller check pod-uid"
-	echo "splunk-controller add pod-uid [meta-data]"
-	echo "splunk-controller remove pod-uid"
+        echo "Usage: -"
+        echo "splunk-controller check pod-uid"
+        echo "splunk-controller add pod-uid [meta-data]"
+        echo "splunk-controller remove pod-uid"
 }
 
 ###########################################################################
@@ -125,7 +126,7 @@ op=$1
 
 if [[ $# -lt 2 ]]; then
         usage
-	exit 1
+        exit 1
 fi
 
 shift
@@ -139,7 +140,7 @@ case "$op" in
                 ;;
         *)
                 usage
-		exit 1
+                exit 1
 esac
 
 exit $?
